// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ta.Backend.Persistence;

#nullable disable

namespace Ta.Backend.Persistence.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    [Migration("20260920175339_AcademicAttendanceAndEnrollment")]
    partial class AcademicAttendanceAndEnrollment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.AcademicClass", b =>
                {
                    b.Property<Guid>("AcademicClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("academic_class_id");

                    b.Property<bool>("AcademicClassActive")
                        .HasColumnType("boolean")
                        .HasColumnName("academic_class_active");

                    b.Property<int>("AcademicClassCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("academic_class_capacity");

                    b.Property<string>("AcademicClassName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("academic_class_name");

                    b.Property<Guid>("AcademicTermId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_term_id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("lecturer_id");

                    b.HasKey("AcademicClassId")
                        .HasName("pk_academic_class");

                    b.HasIndex("AcademicTermId")
                        .HasDatabaseName("ix_academic_class_academic_term_id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_academic_class_course_id");

                    b.HasIndex("LecturerId")
                        .HasDatabaseName("ix_academic_class_lecturer_id");

                    b.ToTable("academic_class", null, t =>
                        {
                            t.HasCheckConstraint("ck_class_capacity", "academic_class_capacity BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.AcademicSchedule", b =>
                {
                    b.Property<Guid>("AcademicScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("academic_schedule_id");

                    b.Property<Guid>("AcademicClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_class_id");

                    b.Property<int>("AcademicScheduleDayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("academic_schedule_day_of_week");

                    b.Property<TimeOnly>("AcademicScheduleEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("academic_schedule_end");

                    b.Property<TimeOnly>("AcademicScheduleStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("academic_schedule_start");

                    b.Property<string>("AcademicScheduleTimeZone")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("academic_schedule_time_zone");

                    b.Property<DateOnly>("AcademicScheduleValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("academic_schedule_valid_from");

                    b.Property<DateOnly>("AcademicScheduleValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("academic_schedule_valid_until");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("classroom_id");

                    b.HasKey("AcademicScheduleId")
                        .HasName("pk_academic_schedule");

                    b.HasIndex("AcademicClassId")
                        .HasDatabaseName("ix_academic_schedule_academic_class_id");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("ix_academic_schedule_classroom_id");

                    b.ToTable("academic_schedule", null, t =>
                        {
                            t.HasCheckConstraint("ck_schedule_interval", "academic_schedule_day_of_week BETWEEN 0 AND 6 AND academic_schedule_end > academic_schedule_start AND academic_schedule_valid_until >= academic_schedule_valid_from");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.AcademicTerm", b =>
                {
                    b.Property<Guid>("AcademicTermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("academic_term_id");

                    b.Property<bool>("AcademicTermActive")
                        .HasColumnType("boolean")
                        .HasColumnName("academic_term_active");

                    b.Property<DateOnly>("AcademicTermEnd")
                        .HasColumnType("date")
                        .HasColumnName("academic_term_end");

                    b.Property<decimal>("AcademicTermMinimumAttendance")
                        .HasColumnType("numeric")
                        .HasColumnName("academic_term_minimum_attendance");

                    b.Property<string>("AcademicTermName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("academic_term_name");

                    b.Property<DateOnly>("AcademicTermStart")
                        .HasColumnType("date")
                        .HasColumnName("academic_term_start");

                    b.HasKey("AcademicTermId")
                        .HasName("pk_academic_term");

                    b.ToTable("academic_term", null, t =>
                        {
                            t.HasCheckConstraint("ck_term_dates", "academic_term_end >= academic_term_start AND academic_term_minimum_attendance BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.ClassMembership", b =>
                {
                    b.Property<Guid>("ClassMembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("class_membership_id");

                    b.Property<Guid>("AcademicClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_class_id");

                    b.Property<DateTimeOffset>("ClassMembershipValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("class_membership_valid_from");

                    b.Property<DateTimeOffset?>("ClassMembershipValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("class_membership_valid_until");

                    b.Property<Guid>("CourseRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_registration_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("ClassMembershipId")
                        .HasName("pk_class_membership");

                    b.HasIndex("AcademicClassId")
                        .HasDatabaseName("ix_class_membership_academic_class_id");

                    b.HasIndex("CourseRegistrationId")
                        .HasDatabaseName("ix_class_membership_course_registration_id");

                    b.HasIndex("StudentId", "AcademicClassId")
                        .IsUnique()
                        .HasDatabaseName("ix_class_membership_student_id_academic_class_id")
                        .HasFilter("class_membership_valid_until IS NULL");

                    b.ToTable("class_membership", null, t =>
                        {
                            t.HasCheckConstraint("ck_membership_interval", "class_membership_valid_until IS NULL OR class_membership_valid_until >= class_membership_valid_from");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.Classroom", b =>
                {
                    b.Property<Guid>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("classroom_id");

                    b.Property<bool>("ClassroomActive")
                        .HasColumnType("boolean")
                        .HasColumnName("classroom_active");

                    b.Property<string>("ClassroomCode")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("classroom_code");

                    b.Property<string>("ClassroomName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("classroom_name");

                    b.HasKey("ClassroomId")
                        .HasName("pk_classroom");

                    b.HasIndex("ClassroomCode")
                        .IsUnique()
                        .HasDatabaseName("ix_classroom_classroom_code");

                    b.ToTable("classroom", (string)null);
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<bool>("CourseActive")
                        .HasColumnType("boolean")
                        .HasColumnName("course_active");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("course_code");

                    b.Property<int>("CourseCredits")
                        .HasColumnType("integer")
                        .HasColumnName("course_credits");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("course_name");

                    b.Property<Guid>("StudyProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_program_id");

                    b.HasKey("CourseId")
                        .HasName("pk_course");

                    b.HasIndex("CourseCode")
                        .IsUnique()
                        .HasDatabaseName("ix_course_course_code");

                    b.HasIndex("StudyProgramId")
                        .HasDatabaseName("ix_course_study_program_id");

                    b.ToTable("course", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_credits", "course_credits BETWEEN 1 AND 24");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.CourseRegistration", b =>
                {
                    b.Property<Guid>("CourseRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("course_registration_id");

                    b.Property<Guid>("AcademicTermId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_term_id");

                    b.Property<string>("CourseRegistrationReviewNote")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("course_registration_review_note");

                    b.Property<DateTimeOffset?>("CourseRegistrationReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("course_registration_reviewed_at");

                    b.Property<Guid?>("CourseRegistrationReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_registration_reviewer_id");

                    b.Property<string>("CourseRegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("course_registration_status");

                    b.Property<DateTimeOffset?>("CourseRegistrationSubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("course_registration_submitted_at");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("CourseRegistrationId")
                        .HasName("pk_course_registration");

                    b.HasIndex("AcademicTermId")
                        .HasDatabaseName("ix_course_registration_academic_term_id");

                    b.HasIndex("CourseRegistrationReviewerId")
                        .HasDatabaseName("ix_course_registration_course_registration_reviewer_id");

                    b.HasIndex("StudentId", "AcademicTermId")
                        .IsUnique()
                        .HasDatabaseName("ix_course_registration_student_id_academic_term_id");

                    b.ToTable("course_registration", null, t =>
                        {
                            t.HasCheckConstraint("ck_registration_status", "course_registration_status IN ('draft','submitted','corrections','approved','withdrawn')");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.CourseRegistrationItem", b =>
                {
                    b.Property<Guid>("CourseRegistrationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("course_registration_item_id");

                    b.Property<Guid>("AcademicClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_class_id");

                    b.Property<Guid>("CourseRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_registration_id");

                    b.HasKey("CourseRegistrationItemId")
                        .HasName("pk_course_registration_item");

                    b.HasIndex("AcademicClassId")
                        .HasDatabaseName("ix_course_registration_item_academic_class_id");

                    b.HasIndex("CourseRegistrationId", "AcademicClassId")
                        .IsUnique()
                        .HasDatabaseName("ix_course_registration_item_course_registration_id_6f860edfe16a");

                    b.ToTable("course_registration_item", (string)null);
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.DeviceRoomAssignment", b =>
                {
                    b.Property<Guid>("DeviceRoomAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_room_assignment_id");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("classroom_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("DeviceRoomAssignmentValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_room_assignment_valid_from");

                    b.Property<DateTimeOffset?>("DeviceRoomAssignmentValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_room_assignment_valid_until");

                    b.HasKey("DeviceRoomAssignmentId")
                        .HasName("pk_device_room_assignment");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("ix_device_room_assignment_classroom_id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_room_assignment_device_id")
                        .HasFilter("device_room_assignment_valid_until IS NULL");

                    b.ToTable("device_room_assignment", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_room_interval", "device_room_assignment_valid_until IS NULL OR device_room_assignment_valid_until >= device_room_assignment_valid_from");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.Lecturer", b =>
                {
                    b.Property<Guid>("LecturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("lecturer_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("LecturerNumber")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("lecturer_number");

                    b.HasKey("LecturerId")
                        .HasName("pk_lecturer");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_lecturer_account_id");

                    b.HasIndex("LecturerNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_lecturer_lecturer_number");

                    b.ToTable("lecturer", (string)null);
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.SessionRoster", b =>
                {
                    b.Property<Guid>("SessionRosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_roster_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TeachingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("teaching_session_id");

                    b.HasKey("SessionRosterId")
                        .HasName("pk_session_roster");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_session_roster_student_id");

                    b.HasIndex("TeachingSessionId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_session_roster_teaching_session_id_student_id");

                    b.ToTable("session_roster", (string)null);
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("AdvisorLecturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("advisor_lecturer_id");

                    b.Property<int>("StudentEntryYear")
                        .HasColumnType("integer")
                        .HasColumnName("student_entry_year");

                    b.Property<string>("StudentIdentityId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("student_identity_id");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("student_number");

                    b.Property<string>("StudentPhone")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("student_phone");

                    b.Property<Guid>("StudyProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_program_id");

                    b.HasKey("StudentId")
                        .HasName("pk_student");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_account_id");

                    b.HasIndex("AdvisorLecturerId")
                        .HasDatabaseName("ix_student_advisor_lecturer_id");

                    b.HasIndex("StudentIdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_student_identity_id");

                    b.HasIndex("StudentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_student_student_number");

                    b.HasIndex("StudyProgramId")
                        .HasDatabaseName("ix_student_study_program_id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.StudyProgram", b =>
                {
                    b.Property<Guid>("StudyProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("study_program_id");

                    b.Property<bool>("StudyProgramActive")
                        .HasColumnType("boolean")
                        .HasColumnName("study_program_active");

                    b.Property<string>("StudyProgramCode")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("study_program_code");

                    b.Property<string>("StudyProgramName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("study_program_name");

                    b.HasKey("StudyProgramId")
                        .HasName("pk_study_program");

                    b.HasIndex("StudyProgramCode")
                        .IsUnique()
                        .HasDatabaseName("ix_study_program_study_program_code");

                    b.ToTable("study_program", (string)null);
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.TeachingSession", b =>
                {
                    b.Property<Guid>("TeachingSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("teaching_session_id");

                    b.Property<Guid>("AcademicClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_class_id");

                    b.Property<Guid?>("AcademicScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_schedule_id");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("classroom_id");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("lecturer_id");

                    b.Property<Guid?>("ReplacesTeachingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaces_teaching_session_id");

                    b.Property<int>("TeachingSessionCheckinMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("teaching_session_checkin_minutes");

                    b.Property<int>("TeachingSessionCourseCredits")
                        .HasColumnType("integer")
                        .HasColumnName("teaching_session_course_credits");

                    b.Property<string>("TeachingSessionCourseName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("teaching_session_course_name");

                    b.Property<int>("TeachingSessionEarlyMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("teaching_session_early_minutes");

                    b.Property<DateTimeOffset>("TeachingSessionEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("teaching_session_end");

                    b.Property<int>("TeachingSessionLateMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("teaching_session_late_minutes");

                    b.Property<long>("TeachingSessionRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("teaching_session_revision");

                    b.Property<bool>("TeachingSessionRosterFrozen")
                        .HasColumnType("boolean")
                        .HasColumnName("teaching_session_roster_frozen");

                    b.Property<DateTimeOffset>("TeachingSessionStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("teaching_session_start");

                    b.Property<string>("TeachingSessionStatus")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("teaching_session_status");

                    b.HasKey("TeachingSessionId")
                        .HasName("pk_teaching_session");

                    b.HasIndex("AcademicScheduleId")
                        .HasDatabaseName("ix_teaching_session_academic_schedule_id");

                    b.HasIndex("LecturerId")
                        .HasDatabaseName("ix_teaching_session_lecturer_id");

                    b.HasIndex("ReplacesTeachingSessionId")
                        .HasDatabaseName("ix_teaching_session_replaces_teaching_session_id");

                    b.HasIndex("AcademicClassId", "TeachingSessionStart")
                        .IsUnique()
                        .HasDatabaseName("ix_teaching_session_academic_class_id_teaching_session_start")
                        .HasFilter("teaching_session_status <> 'cancelled'");

                    b.HasIndex("ClassroomId", "TeachingSessionStart")
                        .HasDatabaseName("ix_teaching_session_classroom_id_teaching_session_start");

                    b.ToTable("teaching_session", null, t =>
                        {
                            t.HasCheckConstraint("ck_session_interval", "teaching_session_end > teaching_session_start AND teaching_session_early_minutes BETWEEN 0 AND 180 AND teaching_session_late_minutes BETWEEN 0 AND 180 AND teaching_session_checkin_minutes >= teaching_session_late_minutes");

                            t.HasCheckConstraint("ck_session_status", "teaching_session_status IN ('scheduled','closed','cancelled')");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Attendance.AttendanceDecision", b =>
                {
                    b.Property<Guid>("AttendanceDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_decision_id");

                    b.Property<DateTimeOffset>("AttendanceDecisionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attendance_decision_at");

                    b.Property<string>("AttendanceDecisionOutcome")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("attendance_decision_outcome");

                    b.Property<Guid>("AttendanceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_event_id");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid?>("TeachingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("teaching_session_id");

                    b.HasKey("AttendanceDecisionId")
                        .HasName("pk_attendance_decision");

                    b.HasIndex("AttendanceEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_decision_attendance_event_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_attendance_decision_student_id");

                    b.HasIndex("TeachingSessionId")
                        .HasDatabaseName("ix_attendance_decision_teaching_session_id");

                    b.ToTable("attendance_decision", (string)null);
                });

            modelBuilder.Entity("Ta.Backend.Features.Attendance.AttendanceEvent", b =>
                {
                    b.Property<Guid>("AttendanceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_event_id");

                    b.Property<string>("AttendanceGalleryVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("attendance_gallery_version");

                    b.Property<string>("AttendanceIdentityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("attendance_identity_id");

                    b.Property<DateTimeOffset>("AttendanceOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attendance_occurred_at");

                    b.Property<string>("AttendancePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attendance_payload");

                    b.Property<string>("AttendancePayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attendance_payload_hash");

                    b.Property<DateTimeOffset>("AttendanceReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attendance_received_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_id");

                    b.HasKey("AttendanceEventId")
                        .HasName("pk_attendance_event");

                    b.HasIndex("AttendanceIdentityId", "AttendanceOccurredAt")
                        .HasDatabaseName("ix_attendance_identity_occurred_at");

                    b.HasIndex("DeviceId", "AttendanceOccurredAt")
                        .HasDatabaseName("ix_attendance_device_occurred_at");

                    b.ToTable("attendance_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_occurred_at", "attendance_occurred_at > '1970-01-01T00:00:00Z'::timestamptz");

                            t.HasCheckConstraint("ck_attendance_payload_hash", "attendance_payload_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_attendance_payload_object", "jsonb_typeof(attendance_payload) = 'object'");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Attendance.SessionAttendance", b =>
                {
                    b.Property<Guid>("SessionAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_attendance_id");

                    b.Property<Guid?>("AttendanceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_event_id");

                    b.Property<decimal>("SessionAttendanceLateMinutes")
                        .HasColumnType("numeric")
                        .HasColumnName("session_attendance_late_minutes");

                    b.Property<DateTimeOffset?>("SessionAttendanceOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("session_attendance_occurred_at");

                    b.Property<long>("SessionAttendanceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("session_attendance_revision");

                    b.Property<string>("SessionAttendanceSource")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("session_attendance_source");

                    b.Property<string>("SessionAttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("session_attendance_status");

                    b.Property<DateTimeOffset>("SessionAttendanceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("session_attendance_updated_at");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TeachingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("teaching_session_id");

                    b.HasKey("SessionAttendanceId")
                        .HasName("pk_session_attendance");

                    b.HasIndex("AttendanceEventId")
                        .HasDatabaseName("ix_session_attendance_attendance_event_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_session_attendance_student_id");

                    b.HasIndex("TeachingSessionId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_session_attendance_teaching_session_id_student_id");

                    b.ToTable("session_attendance", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_status", "session_attendance_status IN ('present','late','excused','absent') AND session_attendance_source IN ('automatic','manual')");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Audit.AuditRecord", b =>
                {
                    b.Property<Guid>("AuditRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_record_id");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("audit_action");

                    b.Property<string>("AuditActor")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("audit_actor");

                    b.Property<string>("AuditDetails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("audit_details");

                    b.Property<DateTimeOffset>("AuditOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_occurred_at");

                    b.Property<string>("AuditResource")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("audit_resource");

                    b.HasKey("AuditRecordId")
                        .HasName("pk_audit_record");

                    b.HasIndex("AuditOccurredAt")
                        .HasDatabaseName("ix_audit_record_audit_occurred_at");

                    b.ToTable("audit_record", (string)null);
                });

            modelBuilder.Entity("Ta.Backend.Features.Biometrics.BiometricEnrollment", b =>
                {
                    b.Property<Guid>("BiometricEnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("biometric_enrollment_id");

                    b.Property<string>("BiometricEnrollmentConsentVersion")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("biometric_enrollment_consent_version");

                    b.Property<DateTimeOffset>("BiometricEnrollmentConsentedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("biometric_enrollment_consented_at");

                    b.Property<DateTimeOffset>("BiometricEnrollmentCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("biometric_enrollment_created_at");

                    b.Property<string>("BiometricEnrollmentReviewNote")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("biometric_enrollment_review_note");

                    b.Property<string>("BiometricEnrollmentStatus")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("biometric_enrollment_status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("BiometricEnrollmentId")
                        .HasName("pk_biometric_enrollment");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_biometric_enrollment_student_id")
                        .HasFilter("biometric_enrollment_status = 'draft'");

                    b.ToTable("biometric_enrollment", null, t =>
                        {
                            t.HasCheckConstraint("ck_enrollment_status", "biometric_enrollment_status IN ('draft','submitted','approved','rejected','revoked')");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Biometrics.BiometricTemplate", b =>
                {
                    b.Property<Guid>("BiometricTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("biometric_template_id");

                    b.Property<Guid>("BiometricEnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("biometric_enrollment_id");

                    b.Property<bool>("BiometricTemplateActive")
                        .HasColumnType("boolean")
                        .HasColumnName("biometric_template_active");

                    b.Property<double>("BiometricTemplateAlignmentError")
                        .HasColumnType("double precision")
                        .HasColumnName("biometric_template_alignment_error");

                    b.Property<DateTimeOffset>("BiometricTemplateCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("biometric_template_created_at");

                    b.Property<double>("BiometricTemplateDetectionScore")
                        .HasColumnType("double precision")
                        .HasColumnName("biometric_template_detection_score");

                    b.Property<byte[]>("BiometricTemplateEmbedding")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("biometric_template_embedding");

                    b.Property<string>("BiometricTemplateImageSha256")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("biometric_template_image_sha256");

                    b.Property<string>("BiometricTemplateModelSha256")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("biometric_template_model_sha256");

                    b.Property<string>("BiometricTemplatePose")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("biometric_template_pose");

                    b.HasKey("BiometricTemplateId")
                        .HasName("pk_biometric_template");

                    b.HasIndex("BiometricEnrollmentId", "BiometricTemplateImageSha256")
                        .IsUnique()
                        .HasDatabaseName("ix_biometric_template_biometric_enrollment_id_biom_fc10065a3402");

                    b.ToTable("biometric_template", null, t =>
                        {
                            t.HasCheckConstraint("ck_template_size", "octet_length(biometric_template_embedding) = 2048");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Biometrics.GalleryRelease", b =>
                {
                    b.Property<long>("GalleryReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("gallery_release_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GalleryReleaseId"));

                    b.Property<string>("GalleryDocument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gallery_document");

                    b.Property<string>("GalleryEtag")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("gallery_etag");

                    b.Property<string>("GalleryModelSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("gallery_model_sha256");

                    b.Property<DateTimeOffset>("GalleryPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gallery_published_at");

                    b.Property<int>("GalleryTemplateCount")
                        .HasColumnType("integer")
                        .HasColumnName("gallery_template_count");

                    b.Property<string>("GalleryVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("gallery_version");

                    b.HasKey("GalleryReleaseId")
                        .HasName("pk_gallery_release");

                    b.HasIndex("GalleryVersion")
                        .IsUnique()
                        .HasDatabaseName("uq_gallery_version");

                    b.ToTable("gallery_release", null, t =>
                        {
                            t.HasCheckConstraint("ck_gallery_document_size", "octet_length(gallery_document) <= 33554432");

                            t.HasCheckConstraint("ck_gallery_model_sha256", "gallery_model_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_gallery_template_count", "gallery_template_count BETWEEN 0 AND 10000");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Devices.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("DeviceCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_created_at");

                    b.Property<DateTimeOffset>("DeviceCredentialChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_credential_changed_at");

                    b.Property<bool>("DeviceEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("device_enabled");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_token_hash");

                    b.HasKey("DeviceId")
                        .HasName("pk_device");

                    b.HasIndex("DeviceTokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_device_token_hash");

                    b.ToTable("device", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_id", "length(device_id) BETWEEN 1 AND 256");

                            t.HasCheckConstraint("ck_device_token_hash", "device_token_hash ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Identity.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("AccountCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("account_created_at");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("account_email");

                    b.Property<int>("AccountFailedLogins")
                        .HasColumnType("integer")
                        .HasColumnName("account_failed_logins");

                    b.Property<DateTimeOffset?>("AccountLockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("account_locked_until");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountPasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("account_password_hash");

                    b.Property<string>("AccountRole")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("account_role");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("account_status");

                    b.HasKey("AccountId")
                        .HasName("pk_account");

                    b.HasIndex("AccountEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_account_account_email");

                    b.ToTable("account", null, t =>
                        {
                            t.HasCheckConstraint("ck_account_role", "account_role IN ('administrator','lecturer','student')");

                            t.HasCheckConstraint("ck_account_status", "account_status IN ('pending','approved','disabled','rejected')");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Identity.AccountSession", b =>
                {
                    b.Property<Guid>("AccountSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("account_session_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("AccountSessionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("account_session_expires_at");

                    b.Property<bool>("AccountSessionRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("account_session_revoked");

                    b.Property<string>("AccountSessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("account_session_token_hash");

                    b.HasKey("AccountSessionId")
                        .HasName("pk_account_session");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_session_account_id");

                    b.HasIndex("AccountSessionTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_account_session_account_session_token_hash");

                    b.ToTable("account_session", (string)null);
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.AcademicClass", b =>
                {
                    b.HasOne("Ta.Backend.Features.AcademicManagement.AcademicTerm", null)
                        .WithMany()
                        .HasForeignKey("AcademicTermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academic_class_academic_term_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academic_class_course_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.Lecturer", null)
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academic_class_lecturer_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.AcademicSchedule", b =>
                {
                    b.HasOne("Ta.Backend.Features.AcademicManagement.AcademicClass", null)
                        .WithMany()
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academic_schedule_academic_class_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.Classroom", null)
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academic_schedule_classroom_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.ClassMembership", b =>
                {
                    b.HasOne("Ta.Backend.Features.AcademicManagement.AcademicClass", null)
                        .WithMany()
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_membership_academic_class_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.CourseRegistration", null)
                        .WithMany()
                        .HasForeignKey("CourseRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_membership_course_registration_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_membership_student_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.Course", b =>
                {
                    b.HasOne("Ta.Backend.Features.AcademicManagement.StudyProgram", null)
                        .WithMany()
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_study_program_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.CourseRegistration", b =>
                {
                    b.HasOne("Ta.Backend.Features.AcademicManagement.AcademicTerm", null)
                        .WithMany()
                        .HasForeignKey("AcademicTermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_registration_academic_term_id");

                    b.HasOne("Ta.Backend.Features.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("CourseRegistrationReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_course_registration_course_registration_reviewer_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_registration_student_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.CourseRegistrationItem", b =>
                {
                    b.HasOne("Ta.Backend.Features.AcademicManagement.AcademicClass", null)
                        .WithMany()
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_registration_item_academic_class_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.CourseRegistration", null)
                        .WithMany()
                        .HasForeignKey("CourseRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_registration_item_course_registration_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.DeviceRoomAssignment", b =>
                {
                    b.HasOne("Ta.Backend.Features.AcademicManagement.Classroom", null)
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_room_assignment_classroom_id");

                    b.HasOne("Ta.Backend.Features.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_room_assignment_device_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.Lecturer", b =>
                {
                    b.HasOne("Ta.Backend.Features.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lecturer_account_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.SessionRoster", b =>
                {
                    b.HasOne("Ta.Backend.Features.AcademicManagement.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_roster_student_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.TeachingSession", null)
                        .WithMany()
                        .HasForeignKey("TeachingSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_roster_teaching_session_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.Student", b =>
                {
                    b.HasOne("Ta.Backend.Features.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_account_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.Lecturer", null)
                        .WithMany()
                        .HasForeignKey("AdvisorLecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_advisor_lecturer_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.StudyProgram", null)
                        .WithMany()
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_study_program_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.AcademicManagement.TeachingSession", b =>
                {
                    b.HasOne("Ta.Backend.Features.AcademicManagement.AcademicClass", null)
                        .WithMany()
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teaching_session_academic_class_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.AcademicSchedule", null)
                        .WithMany()
                        .HasForeignKey("AcademicScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_teaching_session_academic_schedule_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.Classroom", null)
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teaching_session_classroom_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.Lecturer", null)
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teaching_session_lecturer_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.TeachingSession", null)
                        .WithMany()
                        .HasForeignKey("ReplacesTeachingSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_teaching_session_replaces_teaching_session_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.Attendance.AttendanceDecision", b =>
                {
                    b.HasOne("Ta.Backend.Features.Attendance.AttendanceEvent", null)
                        .WithMany()
                        .HasForeignKey("AttendanceEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_decision_attendance_event_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attendance_decision_student_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.TeachingSession", null)
                        .WithMany()
                        .HasForeignKey("TeachingSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attendance_decision_teaching_session_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.Attendance.AttendanceEvent", b =>
                {
                    b.HasOne("Ta.Backend.Features.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_event_device");
                });

            modelBuilder.Entity("Ta.Backend.Features.Attendance.SessionAttendance", b =>
                {
                    b.HasOne("Ta.Backend.Features.Attendance.AttendanceEvent", null)
                        .WithMany()
                        .HasForeignKey("AttendanceEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_session_attendance_attendance_event_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_attendance_student_id");

                    b.HasOne("Ta.Backend.Features.AcademicManagement.TeachingSession", null)
                        .WithMany()
                        .HasForeignKey("TeachingSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_attendance_teaching_session_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.Biometrics.BiometricEnrollment", b =>
                {
                    b.HasOne("Ta.Backend.Features.AcademicManagement.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_biometric_enrollment_student_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.Biometrics.BiometricTemplate", b =>
                {
                    b.HasOne("Ta.Backend.Features.Biometrics.BiometricEnrollment", null)
                        .WithMany()
                        .HasForeignKey("BiometricEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_biometric_template_biometric_enrollment_id");
                });

            modelBuilder.Entity("Ta.Backend.Features.Identity.AccountSession", b =>
                {
                    b.HasOne("Ta.Backend.Features.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_session_account_id");
                });
#pragma warning restore 612, 618
        }
    }
}
