// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ta.Backend.Persistence;

#nullable disable

namespace Ta.Backend.Persistence.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    partial class BackendDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ta.Backend.Features.Attendance.AttendanceEvent", b =>
                {
                    b.Property<Guid>("AttendanceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_event_id");

                    b.Property<string>("AttendanceGalleryVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("attendance_gallery_version");

                    b.Property<string>("AttendanceIdentityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("attendance_identity_id");

                    b.Property<DateTimeOffset>("AttendanceOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attendance_occurred_at");

                    b.Property<string>("AttendancePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attendance_payload");

                    b.Property<string>("AttendancePayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attendance_payload_hash");

                    b.Property<DateTimeOffset>("AttendanceReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attendance_received_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_id");

                    b.HasKey("AttendanceEventId")
                        .HasName("pk_attendance_event");

                    b.HasIndex("AttendanceIdentityId", "AttendanceOccurredAt")
                        .HasDatabaseName("ix_attendance_identity_occurred_at");

                    b.HasIndex("DeviceId", "AttendanceOccurredAt")
                        .HasDatabaseName("ix_attendance_device_occurred_at");

                    b.ToTable("attendance_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_occurred_at", "attendance_occurred_at > '1970-01-01T00:00:00Z'::timestamptz");

                            t.HasCheckConstraint("ck_attendance_payload_hash", "attendance_payload_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_attendance_payload_object", "jsonb_typeof(attendance_payload) = 'object'");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Biometrics.GalleryRelease", b =>
                {
                    b.Property<long>("GalleryReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("gallery_release_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GalleryReleaseId"));

                    b.Property<string>("GalleryDocument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gallery_document");

                    b.Property<string>("GalleryEtag")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("gallery_etag");

                    b.Property<string>("GalleryModelSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("gallery_model_sha256");

                    b.Property<DateTimeOffset>("GalleryPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gallery_published_at");

                    b.Property<int>("GalleryTemplateCount")
                        .HasColumnType("integer")
                        .HasColumnName("gallery_template_count");

                    b.Property<string>("GalleryVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("gallery_version");

                    b.HasKey("GalleryReleaseId")
                        .HasName("pk_gallery_release");

                    b.HasIndex("GalleryVersion")
                        .IsUnique()
                        .HasDatabaseName("uq_gallery_version");

                    b.ToTable("gallery_release", null, t =>
                        {
                            t.HasCheckConstraint("ck_gallery_document_size", "octet_length(gallery_document) <= 33554432");

                            t.HasCheckConstraint("ck_gallery_model_sha256", "gallery_model_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_gallery_template_count", "gallery_template_count BETWEEN 0 AND 10000");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Devices.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("DeviceCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_created_at");

                    b.Property<DateTimeOffset>("DeviceCredentialChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_credential_changed_at");

                    b.Property<bool>("DeviceEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("device_enabled");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_token_hash");

                    b.HasKey("DeviceId")
                        .HasName("pk_device");

                    b.HasIndex("DeviceTokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_device_token_hash");

                    b.ToTable("device", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_id", "length(device_id) BETWEEN 1 AND 256");

                            t.HasCheckConstraint("ck_device_token_hash", "device_token_hash ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("Ta.Backend.Features.Attendance.AttendanceEvent", b =>
                {
                    b.HasOne("Ta.Backend.Features.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_event_device");
                });
#pragma warning restore 612, 618
        }
    }
}
